// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT.
  
  import { DOCUMENT_ROOT_ID } from '@/config/client';
  import React from 'react';
  import { StoryPage } from '@/pages';
  import { type StoryProps } from '@/components';
  import { hydrateRoot } from 'react-dom/client';
  import { inject } from '@vercel/analytics';
  import writMdJson from '@/contexts/data/writ.json';
  
  function mount(): void {
    let mountingEl = document.getElementById(DOCUMENT_ROOT_ID);
    if (mountingEl == null) {
      mountingEl = document.createElement('div');
      mountingEl.id = DOCUMENT_ROOT_ID;
      document.body.appendChild(mountingEl);
    }
    const story = writMdJson.metadata.find(({ key }) => key === '0102');
    let genres: string[] = [];
    if (story) {
      genres = story.genres;
    }
    const props: StoryProps = {
      author: 'Irving Washington',
      content: `#### A Recounting of A World Order

&gt; An omniscient viewpoint vignette of the founding of an influential power ring. Brought forth in small glimpses of its development over centuries.

#### The Present, and Unwrapping It

&gt; Current members debate if there is meaning behind the &#x60;couch gag&#x60; incident, and what a proper response would be if one was taken.

#### Heaven has no easy exit.

&gt; Things go sideways fast, as the No Name Cult demonstrates the incomprehensible lengths that a will for power can go.

#### A family prophecy, one that isn&#x27;t bullshit.

&gt; We travel alongside a survivor&#x27;s exit from the mountains.
&gt; Martin shoots a bear 9 times in the eye.
&gt; He recovers the fallout.`,
      description: 'The leaders of the free world meet to discuss the recent exposition.',
      genres,
      imgAlt: 'The leaders of the free world meet to discuss the recent exposition.',
      imgSrc: '/mountaincabin.jpg',
      title: 'Meanwhile, Under the Mountains'
    };
    hydrateRoot(
      mountingEl,
        <StoryPage {...props} />
    );
  }
  
  if (process.env.NODE_ENV === 'production') {
    inject({ mode: 'production' });
  }
  
  mount();
    
  