// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT.
  
  import { DOCUMENT_ROOT_ID } from '@/config/client';
  import React from 'react';
  import { StoryPage } from '@/pages';
  import { type StoryProps } from '@/components';
  import { hydrateRoot } from 'react-dom/client';
  import { inject } from '@vercel/analytics';
  import writMdJson from '@/contexts/data/writ.json';
  
  function mount(): void {
    let mountingEl = document.getElementById(DOCUMENT_ROOT_ID);
    if (mountingEl == null) {
      mountingEl = document.createElement('div');
      mountingEl.id = DOCUMENT_ROOT_ID;
      document.body.appendChild(mountingEl);
    }
    const story = writMdJson.metadata.find(({ key }) => key === '0101');
    let genres: string[] = [];
    if (story) {
      genres = story.genres;
    }
    const props: StoryProps = {
      author: 'Washington Irving',
      content: `&gt; Casting Calls
&gt; A brief 15 min exploration of each character preparing for the voyage/expedition. Characters are humans. Humans are beautiful pieces of shit. They have ulterior motives. They think theyre smarter than one another, smart people think that especially. Characters that are real receive love because people have an easier time loving in others what they can&#x27;t necessarily learn as easily to love about themselves. Psychology is a witchy woman in the night. 6 characters. 6 different motives. 6 people that go poof into the anonymity of anthology in the end of it. Make them enjoyable while they last.
&gt;
&gt; What kind of person do you want to tell a story about?
&gt;
&gt; What makes a scumbag lovable? We see ourselves being able to make the choices they make. Maybe we don&#x27;t but we could.  

## Arya  

Arya struggled to open her eyes on Saturday mornings. Life was tiring, and there would likely be something to do until she died. She didn&#x27;t dream as often as she did when she was younger. Her dreams were scarce, and if she had paused for a moment to reflect on it, she may have felt that she missed that state of quasi-existence and pseudo-experience. There was something about not dreaming, waking up and being rooted firmly in the skin around you. It was the black and white of it all. Without dreams, you were just living until you were dead. Like flipping a switch. She slept deeply most nights regardless. When she awoke, she had breathing, sentient dreams that kept her focused and driven; they were visible and palpable to her, and they made her cutting, and smart, and untrustworthy; But it was 10:56 AM mountain time, and she hadn&#x27;t woken up yet.  

Around her, there was largely deterioration. Her apartment was cramped. She was occupying the couch, which lined the south wall of the living area of the apartment. The couch was missing its front right leg, and sloped downwards awkwardly. She had no blanket on. The sun cast dim, blurred rays through a severely smudged window, and those rays landed on her face and upper body, and warmed her. She was unconventionally breathtaking, and the radiance that projected forth from her glowing sunshone skin seemed wildly out of place here, in the decadence of this downtown Denver, seven hundred and sixty square foot apartment. Her arm hung limp off the side of the couch, and threatened to touch the floor, which was carpet, that had patches that had mildewed from moisture, and had begun to wick white towards the wisps at the tops, and had become crunchy to step on. It was beyond saving, even with the most aggressive of shock-vacuums.  

Just beyond where her arm hung, there was a coffee table that she had thrifted curbside, and lugged back to the apartment. It was chipped away at in the wooden legs, and on the face of the table, littered dozens of etchings in. If the table was clean (it wasn&#x27;t), you would have been able to see the conglomeration of etchings, and what they came together to form; it was a scene of a cliff overlooking a dim array of townhouses and streets over the crest of the hillcliff, with the sun setting behind it and the early emergence of stars. It was a vantage point over a town that had no residents, no movement, nothing worth watching, but she had created it from the wastes of a wooden table that collected rainwater for several days on the side of the road. It was during a period in which she was forcing herself off cocaine. During that period she had time to kill. So much time to pin down and wrestle with, to take a knife to and stab over and over again, to strangle with a garrote until she was red in the face, dripping sweat and poised inches over time&#x27;s lifeless body with the bugging blood dripping eyes and that dumb dead open mouth expression. She had resented that time. She had loved good cocaine. But like many things she had loved before, it was terrible for her and brought out a side to her she&#x27;d prefer to leave stuffed down somewhere altogether lower, more distant,. It made the living, breathing dream hazy and distant.  

She had no benefactors. She had, perhaps, fewer real friends. She often found she had opporunities thrust upon her, and you could do a lot with that, if you were always looking for something.

---  

## Over The Hills And Further Away

&gt; The descent into the forgotten city of Rheny&#x27;ah, absurd splendor, wonder, and disbelief at the nature of the decline. Go very hard with descriptive architecture language. Lean on tapestries for windows into older civilizations. This should lean as a fulfillment of the mysterious message that was receieved and trasnscribed in part 1.

## The Moment Before The End Of The World And What Was On The Minds Of Our Prophets

&gt; Go through the thoughts of our researchers before the cavern floor gives out and the sarcophigial chamber is revealed. In this chamber, is where we encounter the couch gag relic. 

## Simpsons Did It, Simpsons Did It
`,
      description: 'A discovery is made during a remote expedition to Antarctica that begins to unravel the fabric of the human storyline.',
      genres,
      imgAlt: 'A discovery is made during a remote expedition to Antarctica that begins to unravel the fabric of the human storyline.',
      imgSrc: '/snow-red.webp',
      title: 'The Origin, and What Came Before It'
    };
    hydrateRoot(
      mountingEl,
        <StoryPage {...props} />
    );
  }
  
  if (process.env.NODE_ENV === 'production') {
    inject({ mode: 'production' });
  }
  
  mount();
    
  