// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT.

import { DOCUMENT_ROOT_ID } from '@/config/client';
import React from 'react';
import { StoryPage } from '@/pages';
import { type StoryProps } from '@/components';
import { hydrateRoot } from 'react-dom/client';
import writMdJson from '@/contexts/data/writ.json';

function mount(): void {
  let mountingEl = document.getElementById(DOCUMENT_ROOT_ID);
  if (mountingEl == null) {
    mountingEl = document.createElement('div');
    mountingEl.id = DOCUMENT_ROOT_ID;
    document.body.appendChild(mountingEl);
  }
  const story = writMdJson.metadata.find(({ key }) => key === '0105');
  let genres: string[] = [];
  if (story) {
    genres = story.genres;
  }
  const props: StoryProps = {
    author: 'Irving Washington',
    content: `#### a modern hive mind

Colorado has an average of five to seven thousand wildfires a year. It&#x27;s been absolutely ravaged by an increasingly dry climate, coupled with sporadic periods of brief rain, and a population that really loves to smoke. When these wildfires hit, entire towns need to be relocated, highways are shut down (there are only two major highways in Colorado, the I25 that spans North to South, and the I70 which runs the full length of the state East to West, like fucking pioneer times.), and traffic and civilian life comes to all but a standstill for hours, sometimes days, as the wildfire dryrapes the land and leaves the sky a barren red and gray. People are stuck in their cars on the interstate. If you&#x27;re able to exit the highway at all, you&#x27;re coerced into these single lane mountain winding dirt roads that span countless miles, along with the any number of other travelers that dared to make the same venture. Its treacherous as all hell, and that&#x27;s when ground conditions are fine. Some saw this as an issue. Some campaigned to monitor vehicle emissions, some campaigned to have large fines on outdoor smoking, discarding cigarette butts on roadways, leaving embers on campfires, and the like that have been known to start a fire or two. Some didn&#x27;t give a shit at all; and one human, just one human sack of shit had the divine vigor to see this scenario as an opportunity and take it. And that&#x27;s why we&#x27;re telling his story.

Like all monumental ideas, this one was born in an instant. It was a clear, and foreign whispering, an itch in the brain that behaved like any other manner of parasite. It was hot, and uncomfortable, and alive. And the snowball began to roll.

#### A symphony of perspectives

&gt; No name cult decides what&#x27;s going to be the soundtrack to their reckoning, and after iterating for several rounds decides on Back to Black. Then were going to flash to the raid in the mountainfront. Where the police/fire department 

&quot;Well, what about &#x60;Paint it Black&#x60;?&quot;, R.

&quot;Jesus fucking Christ.&quot; T.

There&#x27;s an eruption of snickers. T pulls out 500 dollars in a fat folded wad, held wound with broccoli bands. T hands it off to Z.

&quot;Fucking had to be R.&quot; Z. &quot;Thank you Westworld.&quot;

&quot;I have no idea what&#x27;s going on.&quot; R.

&quot;We had a pool going on who would suggest Paint it Black, it&#x27;s just such a fucking cliche pick dude.&quot; T. 

#### The only nomination that mattered in the end 

&gt; 


`,
    description: 'no-name cult exacts an operation that spirals into control.',
    genres,
    imgAlt: 'no-name cult exacts an operation that spirals into control.',
    imgSrc: 'https://www.chicitysports.com/wp-content/uploads/2020/07/the_simpsons_couch_a_l.0.jpg',
    title: 'trial by fire'
  };
  hydrateRoot(mountingEl, <StoryPage {...props} />);
}

mount();
