// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT.
import { DOCUMENT_ROOT_ID } from '@/config/client';
import React from 'react';
import { StoryPage } from '@/pages';
import { type StoryProps } from '@/components';
import { hydrateRoot } from 'react-dom/client';

function mount(): void {
  let mountingEl = document.getElementById(DOCUMENT_ROOT_ID);
  if (mountingEl == null) {
    mountingEl = document.createElement('div');
    mountingEl.id = DOCUMENT_ROOT_ID;
    document.body.appendChild(mountingEl);
  }
  const props: StoryProps = {
    author: 'Irving Washington',
    content: `#### 
`,
    description: '',
    genres: [],
    imgAlt: '',
    imgSrc: 'https://www.chicitysports.com/wp-content/uploads/2020/07/the_simpsons_couch_a_l.0.jpg',
    title: 'The Common Man and His Common Dream'
  };
  hydrateRoot(mountingEl, <StoryPage {...props} />);
}

mount();
